import {config,fields,singleton,collection} from '@keystatic/core';
import {createElement} from 'react';
export const itemLabel=(props:any):string=>[
  props.value,
  props.fields?.short?.fields?.en?.value,
  props.fields?.title?.fields?.en?.value,
  props.fields?.question?.fields?.en?.value,
  props.fields?.heading?.fields?.en?.value,
  props.fields?.name?.value,
  props.fields?.key?.value,
  props.fields?.en?.value,
  props.value?.filename,
  props.fields?.image?.value?.filename,
  props.fields?.image?.value,
].find(value=>typeof value==='string'&&value.length>0)||'Elemento';
// Schemas are fixed independently of editable content. Local-only administration.
const blogText=(label:string)=>fields.markdoc.inline({label,description:'Usa la barra de formato. Las imágenes y el texto se guardan al pulsar Save.',options:{heading:[2,3,4],bold:true,italic:true,strikethrough:true,orderedList:true,unorderedList:true,blockquote:true,table:true,link:true,divider:true,code:false,codeBlock:false,image:{directory:'public/media/cms/articles/inline',publicPath:'/media/cms/articles/inline/',schema:{alt:fields.text({label:'Descripción accesible',validation:{isRequired:true}}),title:fields.text({label:'Título de la imagen'})}}}});
const bilingualBlogText=(label:string,multiline=false)=>fields.object({es:fields.text({label:'Español',multiline}),en:fields.text({label:'English',multiline})},{label});
const blog=collection({label:'Blog · Artículos',path:'src/content/articles/*',slugField:'entry',format:{data:'json'},columns:['entry','published'],previewUrl:'/cms/blog-preview/?slug={slug}',schema:{
  entry:fields.slug({name:{label:'Nombre del artículo en el panel',validation:{isRequired:true}},slug:{label:'URL del artículo',description:'Misma URL en inglés y español. Usa minúsculas y guiones.',validation:{pattern:{regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/,message:'Solo minúsculas, números y guiones'}}}}),
  published:fields.checkbox({label:'Publicado',description:'Desactivado: borrador visible solo en la previsualización local.',defaultValue:false}),
  image:fields.image({label:'Imagen de portada',directory:'public/media/cms/articles/covers',publicPath:'/media/cms/articles/covers/'}),
  imageAlt:bilingualBlogText('Descripción de la portada'),
  category:bilingualBlogText('Categoría'),title:bilingualBlogText('Título público'),intro:bilingualBlogText('Entradilla',true),
  seoTitle:bilingualBlogText('Título SEO (opcional)'),seoDescription:bilingualBlogText('Descripción SEO (opcional)',true),
  body:fields.object({es:blogText('Artículo en español'),en:blogText('Article in English')},{label:'Contenido del artículo'}),
}});
export default config({storage:{kind:'local'},ui:{brand:{name:'Studio',mark:()=>createElement('img',{src:'/media/cms/settings/logo.png',height:24,alt:'GOXO',style:{background:'#faf7f0',borderRadius:4,padding:3}})},navigation:{'Experiencias':['tours'],'Páginas':['home','way','about','faq','reviews'],'Fotografía y vídeo':['presentation','media','imageAlts'],'Publicaciones':['articles','verifiedReviews'],'Configuración':['settings','interface','legal']}},collections:{articles:blog},singletons:{home:singleton({label:"Portada y catálogo",path:'src/content/site/home',format:{data:'json'},schema:{"title":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título"}),
"description":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Descripción"}),
"claim":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Frase principal"}),
"experiencesTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de las experiencias"}),
"experiencesIntro":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Introducción de las experiencias"}),
"catalogTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título del catálogo"}),
"catalogIntro":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Introducción del catálogo"}),
"finalTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título del contacto final"}),
"finalBody":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Texto del contacto final"})}}),
way:singleton({label:"The GOXO Way",path:'src/content/site/way',format:{data:'json'},schema:{"whyTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de The GOXO Way"}),
"whyIntro":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Introducción de The GOXO Way"}),
"whySupport":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Texto de apoyo"}),
"reasons":fields.array(fields.object({"title":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título"}),
"body":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Texto"}),
"image":fields.image({label:"Fotografía",directory:'public/media/cms/way',publicPath:'/media/cms/way/'}),
"imageAlt":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Descripción de fotografía"})},{label:"Contenido"}),{label:"Motivos para elegir GOXO",itemLabel:itemLabel})}}),
about:singleton({label:"Empresa e historia de Endika",path:'src/content/site/about',format:{data:'json'},schema:{"hostTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de Endika"}),
"hostCaption":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Presentación breve"}),
"hostStory":fields.array(fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Contenido"}),{label:"Historia de Endika",itemLabel:itemLabel}),
"aboutTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título SEO de Acerca de"}),
"aboutClaim":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título principal de Acerca de"}),
"aboutIntro":fields.array(fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Contenido"}),{label:"Introducción de la empresa",itemLabel:itemLabel}),
"aboutCompany":fields.array(fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Contenido"}),{label:"Historia de GOXO",itemLabel:itemLabel}),
"aboutCommitment":fields.array(fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Contenido"}),{label:"Compromiso",itemLabel:itemLabel})}}),
reviews:singleton({label:"Textos de opiniones",path:'src/content/site/reviews',format:{data:'json'},schema:{"reviewsTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de opiniones"}),
"reviewsIntro":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Introducción de opiniones"})}}),
faq:singleton({label:"Preguntas frecuentes",path:'src/content/site/faq',format:{data:'json'},schema:{"faqTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de FAQ"}),
"faqIntro":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Introducción de FAQ"}),
"faqs":fields.array(fields.object({"question":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Pregunta"}),
"answer":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Respuesta"})},{label:"Contenido"}),{label:"Preguntas",itemLabel:itemLabel})}}),
tours:singleton({label:"Experiencias y tours",path:'src/content/site/tours',format:{data:'json'},schema:{"tours":fields.array(fields.object({"id":fields.text({label:"Identificador interno (conservar)",multiline:false,validation:{isRequired:true},}),
"slug":fields.text({label:"URL pública",multiline:false,validation:{isRequired:true,pattern:{regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/,message:'Solo minúsculas, números y guiones'}},}),
"category":fields.text({label:"Categoría",multiline:false,}),
"image":fields.image({label:"Fotografía",directory:'public/media/cms/tours',publicPath:'/media/cms/tours/'}),
"imageAlt":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Descripción de fotografía"}),
"short":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Nombre de tarjeta"}),
"name":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Nombre"}),
"location":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Ubicación"}),
"duration":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Duración"}),
"guests":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Personas"}),
"eyebrow":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"eyebrow"}),
"description":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Descripción"}),
"catalogDescription":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"catalog Description"}),
"story":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Texto ampliado"}),
"seoTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título SEO"}),
"seoDescription":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Descripción SEO"}),
"stops":fields.array(fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Contenido"}),{label:"Paradas",itemLabel:itemLabel}),
"stopCopy":fields.array(fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Contenido"}),{label:"Descripción de cada parada",itemLabel:itemLabel}),
"includes":fields.array(fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Contenido"}),{label:"Incluye",itemLabel:itemLabel}),
"excludes":fields.array(fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Contenido"}),{label:"Propuesta personal",itemLabel:itemLabel}),
"faq":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Información adicional"}),
"immersive":fields.checkbox({label:"immersive",defaultValue:false}),
"galleryAlts":fields.array(fields.object({es:fields.text({label:'Español'}),en:fields.text({label:'English'})}),{label:'Descripción de cada foto de la galería (mismo orden)',itemLabel}),"gallery":fields.array(fields.image({label:"Fotografía",directory:'public/media/cms/tours',publicPath:'/media/cms/tours/'}),{label:"Galería de fotografías",itemLabel:itemLabel}),
"published":fields.checkbox({label:"Publicado",defaultValue:false}),
"number":fields.text({label:"Número",multiline:false,})},{label:"Contenido"}),{label:"Tours",itemLabel:itemLabel})}}),
presentation:singleton({label:'Vídeos y presentación',path:'src/content/site/presentation',format:{data:'json'},schema:{hero:fields.object({poster:fields.image({label:'Imagen de portada',directory:'public/media/cms/presentation',publicPath:'/media/cms/presentation/'}),video:fields.file({label:'Subir vídeo local',directory:'public/media/cms/presentation',publicPath:'/media/cms/presentation/'}),videoUrl:fields.url({label:'URL externa de vídeo (opcional)',description:'Enlace HTTPS directo a MP4/WebM. Tiene prioridad sobre el archivo local.'}),cta:fields.object({es:fields.text({label:'Español',multiline:false}),en:fields.text({label:'English',multiline:false})},{label:"Botón principal"}),pause:fields.object({es:fields.text({label:'Español',multiline:false}),en:fields.text({label:'English',multiline:false})},{label:"Control de reproducción"})},{label:'Vídeo de portada'}),host:fields.object({poster:fields.image({label:'Imagen de portada',directory:'public/media/cms/presentation',publicPath:'/media/cms/presentation/'}),posterAlt:fields.object({es:fields.text({label:'Español',multiline:false}),en:fields.text({label:'English',multiline:false})},{label:"Descripción de la fotografía"}),video:fields.file({label:'Subir vídeo local',directory:'public/media/cms/presentation',publicPath:'/media/cms/presentation/'}),videoUrl:fields.url({label:'URL externa de vídeo (opcional)',description:'Enlace HTTPS directo a MP4/WebM. Tiene prioridad sobre el archivo local.'}),captions:fields.array(fields.object({src:fields.file({label:'Archivo VTT',directory:'public/media/cms/presentation/captions',publicPath:'/media/cms/presentation/captions/'}),lang:fields.select({label:'Idioma',options:[{label:'English',value:'en'},{label:'Español',value:'es'}],defaultValue:'en'}),label:fields.text({label:'Nombre de la pista'})}),{label:'Subtítulos',itemLabel:props=>props.fields.label.value}),play:fields.object({es:fields.text({label:'Español',multiline:false}),en:fields.text({label:'English',multiline:false})},{label:"Botón de reproducción"}),error:fields.object({es:fields.text({label:'Español',multiline:true}),en:fields.text({label:'English',multiline:true})},{label:"Mensaje si falla la reproducción"})},{label:'Presentación de Endika'})}}),
media:singleton({label:"Medios y créditos",path:'src/content/site/media',format:{data:'json'},schema:{"coast":fields.image({label:"coast",directory:'public/media/cms/media',publicPath:'/media/cms/media/'}),
"bilbao":fields.image({label:"bilbao",directory:'public/media/cms/media',publicPath:'/media/cms/media/'}),
"pintxos":fields.image({label:"pintxos",directory:'public/media/cms/media',publicPath:'/media/cms/media/'}),
"rioja":fields.image({label:"rioja",directory:'public/media/cms/media',publicPath:'/media/cms/media/'}),
"panoramas":fields.array(fields.object({"id":fields.text({label:"Identificador interno (conservar)",multiline:false,validation:{isRequired:true},}),
"url":fields.text({label:"URL de verificación",multiline:false,}),
"preview":fields.image({label:"preview",directory:'public/media/cms/media',publicPath:'/media/cms/media/'}),
"title":fields.text({label:"Título",multiline:false,}),
"author":fields.text({label:"author",multiline:false,}),
"source":fields.text({label:"source",multiline:false,}),
"label":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Etiqueta"})},{label:"Contenido"}),{label:"panoramas",itemLabel:itemLabel}),
"video":fields.file({label:"Subir vídeo local",directory:'public/media/cms/media',publicPath:'/media/cms/media/'}),"videoUrl":fields.url({label:"URL externa del vídeo (opcional)",description:"Si se indica, se utiliza en lugar del archivo local. Enlace directo a MP4/WebM."}),
"credits":fields.array(fields.object({"title":fields.text({label:"Título",multiline:false,}),
"author":fields.text({label:"author",multiline:false,}),
"license":fields.text({label:"license",multiline:false,}),
"licenseUrl":fields.text({label:"license Url",multiline:false,}),
"source":fields.text({label:"source",multiline:false,}),
"notes":fields.text({label:"notes",multiline:true,}),
"file":fields.text({label:"file",multiline:false,})},{label:"Contenido"}),{label:"credits",itemLabel:itemLabel}),
"galleries":fields.object({"costa-vasca":fields.array(fields.text({label:"Contenido",multiline:false,}),{label:"costa-vasca",itemLabel:itemLabel}),
"rioja":fields.array(fields.text({label:"Contenido",multiline:false,}),{label:"rioja",itemLabel:itemLabel}),
"pintxos":fields.array(fields.text({label:"Contenido",multiline:false,}),{label:"pintxos",itemLabel:itemLabel}),
"bilbao-cultura":fields.array(fields.text({label:"Contenido",multiline:false,}),{label:"bilbao-cultura",itemLabel:itemLabel}),
"san-sebastian-getaria":fields.array(fields.text({label:"Contenido",multiline:false,}),{label:"san-sebastian-getaria",itemLabel:itemLabel})},{label:"galleries"}),
"labels":fields.object({"/media/gallery-mundaka.webp":fields.text({label:"/media/gallery-mundaka.webp",multiline:false,}),
"/media/gallery-gernika.webp":fields.text({label:"/media/gallery-gernika.webp",multiline:false,}),
"/media/gallery-laguardia.webp":fields.text({label:"/media/gallery-laguardia.webp",multiline:false,}),
"/media/gallery-haro.webp":fields.text({label:"/media/gallery-haro.webp",multiline:false,}),
"/media/gallery-casco-viejo.webp":fields.text({label:"/media/gallery-casco-viejo.webp",multiline:false,}),
"/media/gallery-bar-bilbao.webp":fields.text({label:"/media/gallery-bar-bilbao.webp",multiline:false,}),
"/media/gallery-zubizuri.webp":fields.text({label:"/media/gallery-zubizuri.webp",multiline:false,}),
"/media/gallery-arriaga.webp":fields.text({label:"/media/gallery-arriaga.webp",multiline:false,}),
"/media/gallery-ribera.webp":fields.text({label:"/media/gallery-ribera.webp",multiline:false,}),
"/media/gallery-siete-calles.webp":fields.text({label:"/media/gallery-siete-calles.webp",multiline:false,}),
"/media/san-sebastian-reference.webp":fields.text({label:"/media/san-sebastian-reference.webp",multiline:false,})},{label:"labels"}),
"endika":fields.image({label:"endika",directory:'public/media/cms/media',publicPath:'/media/cms/media/'}),
"grupo":fields.image({label:"grupo",directory:'public/media/cms/media',publicPath:'/media/cms/media/'})}}),
legal:singleton({label:"Páginas legales (borradores)",path:'src/content/site/legal',format:{data:'json'},schema:{"privacy":fields.object({"slug":fields.text({label:"URL pública",multiline:false,validation:{isRequired:true,pattern:{regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/,message:'Solo minúsculas, números y guiones'}},}),
"eyebrow":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"eyebrow"}),
"title":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título"}),
"intro":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"intro"}),
"sections":fields.array(fields.object({"heading":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de sección"}),
"body":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Texto"})},{label:"Contenido"}),{label:"Secciones",itemLabel:itemLabel})},{label:"privacy"}),
"terms":fields.object({"slug":fields.text({label:"URL pública",multiline:false,validation:{isRequired:true,pattern:{regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/,message:'Solo minúsculas, números y guiones'}},}),
"eyebrow":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"eyebrow"}),
"title":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título"}),
"intro":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"intro"}),
"sections":fields.array(fields.object({"heading":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de sección"}),
"body":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Texto"}),
"link":fields.object({"href":fields.text({label:"href",multiline:false,}),
"label":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Etiqueta"})},{label:"Enlace"})},{label:"Contenido"}),{label:"Secciones",itemLabel:itemLabel})},{label:"terms"}),
"cancellation":fields.object({"slug":fields.text({label:"URL pública",multiline:false,validation:{isRequired:true,pattern:{regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/,message:'Solo minúsculas, números y guiones'}},}),
"eyebrow":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"eyebrow"}),
"title":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título"}),
"intro":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"intro"}),
"sections":fields.array(fields.object({"heading":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título de sección"}),
"body":fields.object({"es":fields.text({label:"Español",multiline:true,}),
"en":fields.text({label:"English",multiline:true,})},{label:"Texto"}),
"list":fields.array(fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Contenido"}),{label:"Lista",itemLabel:itemLabel})},{label:"Contenido"}),{label:"Secciones",itemLabel:itemLabel})},{label:"cancellation"})}}),
settings:singleton({label:"Identidad, contacto y SEO",path:'src/content/site/settings',format:{data:'json'},schema:{homeSections:fields.array(fields.object({id:fields.select({label:'Sección',options:[{"label":"Vídeo principal","value":"hero"},{"label":"Experiencias","value":"experiences"},{"label":"The GOXO Way","value":"way"},{"label":"Endika","value":"host"},{"label":"Opiniones","value":"reviews"},{"label":"Preguntas frecuentes","value":"faq"},{"label":"Contacto final","value":"plan"},{"label":"Blog","value":"blog"}],defaultValue:'hero'}),label:fields.text({label:'Nombre en el panel'}),visible:fields.checkbox({label:'Visible',defaultValue:true})}),{label:'Orden y visibilidad de la portada',itemLabel:props=>props.fields.label.value}),navigation:fields.array(fields.object({href:fields.text({label:'Enlace',validation:{isRequired:true,pattern:{regex:/^\/(?!\/)/,message:'Usa una ruta interna que empiece por /'}}}),label:fields.object({es:fields.text({label:'Español'}),en:fields.text({label:'English'})},{label:'Texto del menú'})}),{label:'Menú principal',itemLabel:props=>props.fields.label.fields.en.value}),"name":fields.text({label:"Nombre",multiline:false,}),
"email":fields.text({label:"Correo electrónico",multiline:false,validation:{isRequired:true},}),
"telephone":fields.text({label:"Teléfono",multiline:false,}),
"whatsapp":fields.text({label:"WhatsApp (solo dígitos)",multiline:false,validation:{isRequired:true},}),
"location":fields.text({label:"Ubicación",multiline:false,}),
"logo":fields.image({label:"Logo",directory:'public/media/cms/settings',publicPath:'/media/cms/settings/'}),
"googleReviewsUrl":fields.text({label:"Enlace a Google Reviews",multiline:false,}),
"developerName":fields.text({label:"Desarrollador",multiline:false,}),
"developerTelephone":fields.text({label:"Teléfono del desarrollador",multiline:false,}),
"developerUrl":fields.text({label:"Enlace del desarrollador",multiline:true,}),
"catalogSeoTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título SEO del catálogo"}),
"contactSeoTitle":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Título SEO de contacto"})}}),
verifiedReviews:singleton({label:"Reseñas verificadas",path:'src/content/site/verifiedReviews',format:{data:'json'},schema:{"reviews":fields.array(fields.object({"name":fields.text({label:"Nombre",multiline:false,}),
"rating":fields.integer({label:"Valoración (1–5)"}),
"date":fields.text({label:"Fecha",multiline:false,}),
"url":fields.text({label:"URL de verificación",multiline:false,}),
"body":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Texto"}),
"origin":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Origen de la reseña"}),
"tour":fields.object({"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"tour"})},{label:"Contenido"}),{label:"Opiniones verificadas",itemLabel:itemLabel})}}),
interface:singleton({label:"Menú, botones y textos de interfaz",path:'src/content/site/interface',format:{data:'json'},schema:{"entries":fields.array(fields.object({"key":fields.text({label:"Identificador de traducción (conservar)",multiline:false,validation:{isRequired:true},}),
"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Contenido"}),{label:"Textos",itemLabel:itemLabel})}}),
imageAlts:singleton({label:"Descripciones accesibles de imágenes",path:'src/content/site/imageAlts',format:{data:'json'},schema:{"entries":fields.array(fields.object({"image":fields.text({label:'Ruta de la imagen (conservar)'}),
"es":fields.text({label:"Español",multiline:false,}),
"en":fields.text({label:"English",multiline:false,})},{label:"Contenido"}),{label:"Textos",itemLabel:itemLabel})}})}});
