import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {localizedHref,isPublicProduction} from '../data/urls';
import imageAlts from '../data/image-alts.json';
import {STORAGE_KEY,validateState,safeImage,makeWhatsAppMessage,tourHref} from './state';
function initializePage(){
const events=new AbortController();
const on=(target:any,type:string,handler:any,options:any={})=>target.addEventListener(type,handler,{...options,signal:events.signal});
const $=(selector:string):any=>document.querySelector(selector);
const $$=(selector:string):any[]=>Array.from(document.querySelectorAll(selector));
const hero=document.querySelector<HTMLElement>('#hero');
const header=document.querySelector<HTMLElement>('.site-header');
let headerObserver:IntersectionObserver|undefined;
if(hero&&header){
 const updateHeader=()=>{
  const overVideo=hero.getBoundingClientRect().bottom>header.offsetHeight;
  header.classList.toggle('over-video',overVideo);
  const logo=header.querySelector<HTMLImageElement>('.brand-logo');
  if(logo)logo.src='/media/logo-goxo.png';
 };
 on(window,'scroll',updateHeader,{passive:true});on(window,'resize',updateHeader);
 headerObserver=new IntersectionObserver(updateHeader);headerObserver.observe(hero);updateHeader();
}
const seed=JSON.parse($('#goxo-data').textContent);
const baseIds=seed.tours.map((t:any)=>t.id),sceneIds=seed.media.panoramas.map((p:any)=>p.id);
const defaults={version:1,tours:seed.tours,sceneOrder:sceneIds};
let state=structuredClone(defaults),lang=document.documentElement.lang==='en'?'en':'es';
const isPreview=!isPublicProduction&&(location.pathname==='/admin/'||['true','1'].includes(new URLSearchParams(location.search).get('preview')||''));
try{const raw=isPreview?localStorage.getItem(STORAGE_KEY):null;if(raw)state=validateState(JSON.parse(raw),sceneIds)}catch{}
const copy=(c:any)=>typeof c==='string'?c:(c?.[lang]||c?.es||'');
const say=(es:string,en:string)=>lang==='es'?es:en;
const text=(element:any,content:any)=>{if(element)element.textContent=content};
const localWrite=(key:string,value:string)=>{try{localStorage.setItem(key,value);return true}catch{return false}};
function toast(message:string){const el=$('#toast');text(el,message);el.hidden=false;clearTimeout((toast as any).timer);(toast as any).timer=setTimeout(()=>{el.hidden=true},4500)}
function translated(element:any,content:any){element.dataset.es=content.es;element.dataset.en=content.en;text(element,copy(content))}
function translate(){document.documentElement.lang=lang;$$('[data-es][data-en]').forEach(el=>text(el,el.dataset[lang]));document.dispatchEvent(new Event('goxo:language'))}

const languageLink=$('#language-toggle');
const pagePath=localizedHref(location.pathname,'en');
let languageRequest:AbortController|undefined;
function updateLanguageLinks(){
 $$('a[href]').forEach(a=>{const href=a.getAttribute('href');if(a!==languageLink&&href?.startsWith('/')&&!href.startsWith('//'))a.setAttribute('href',localizedHref(href,lang))});
 if(languageLink){languageLink.href=localizedHref(location.pathname,lang==='en'?'es':'en')+location.search+location.hash;languageLink.textContent=lang==='en'?'ES':'EN';languageLink.setAttribute('aria-label',lang==='en'?'Cambiar a español':'Switch to English')}
}
async function changeLanguage(next:string,push=true){
 languageRequest?.abort();languageRequest=new AbortController();
 const request=languageRequest;
 lang=next==='es'?'es':'en';
 const url=localizedHref(location.pathname,lang)+location.search+location.hash;
 if(push)history.pushState(null,'',url);
 translate();updateLanguageLinks();updateMotionButtons();
 $$('[data-tour-image]').forEach(img=>{const tour=state.tours.find((t:any)=>t.id===img.dataset.tourImage);if(tour)img.alt=copy(tour.imageAlt)});
 $$('img[alt]').forEach(img=>{const alt=imageAlts[new URL(img.src,location.href).pathname];if(img.alt&&alt)img.alt=copy(alt)});
 $$('#contact-tour option').forEach(option=>{const tour=state.tours.find((t:any)=>t.id===option.value);text(option,tour?copy(tour.short):say('Quiero una recomendación','I’d like a recommendation'))});
 $$('#detail-gallery button').forEach((button,i)=>{button.setAttribute('aria-label',say('Ampliar fotografía ','Expand photograph ')+(i+1));text(button.querySelector('span'),say('Ampliar ↗','Expand ↗'))});
 // Read the equivalent static page for its SEO and accessibility labels.
 // Keep the live DOM, video, forms, dialogs and scroll position intact.
 try{
  const response=await fetch(url,{signal:request.signal,cache:'no-cache'});if(!response.ok)return;
  const translatedPage=new DOMParser().parseFromString(await response.text(),'text/html');
  if(events.signal.aborted||request.signal.aborted||location.pathname+location.search+location.hash!==url||document.documentElement.lang!==next)return;
  document.title=translatedPage.title;
  for(const selector of ['meta[name="description"]','link[rel="canonical"]','meta[property^="og:"]','meta[name^="twitter:"]']){const sources=Array.from(translatedPage.querySelectorAll(selector));$$(selector).forEach((target,i)=>{const source=sources[i];if(target&&source)target.setAttribute(target.tagName==='META'?'content':'href',source.getAttribute(target.tagName==='META'?'content':'href')||'')})}
  const graph=translatedPage.querySelector('#seo-graph');if(graph)text($('#seo-graph'),graph.textContent);
  for(const selector of ['[aria-label]','[placeholder]']){const sources=Array.from(translatedPage.querySelectorAll(selector));$$(selector).forEach((target,i)=>{const source=sources[i];if(source&&source.tagName===target.tagName&&target!==languageLink){const attr=selector==='[aria-label]'?'aria-label':'placeholder';target.setAttribute(attr,source.getAttribute(attr)||'')}})}
 }catch{/* Existing bilingual content remains usable when offline. */}
}
languageLink?.addEventListener('click',(event:MouseEvent)=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();void changeLanguage(lang==='en'?'es':'en')});
on(window,'popstate',()=>{if(localizedHref(location.pathname,'en')===pagePath)void changeLanguage(location.pathname.startsWith('/es/')?'es':'en',false)});
updateLanguageLinks();
const menu=$('.menu-toggle');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?say('Cerrar menú','Close menu'):say('Abrir menú','Open menu'));$('#mobile-nav').hidden=!open});
on(document,'keydown',event=>{if(event.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){menu.setAttribute('aria-expanded','false');$('#mobile-nav').hidden=true;menu.focus()}});
$$('#mobile-nav a').forEach(el=>el.addEventListener('click',()=>{$('#mobile-nav').hidden=true;menu.setAttribute('aria-expanded','false')}));
let motionPaused=document.documentElement.dataset.motion==='off';
try{motionPaused=localStorage.getItem('goxo:motion')==='off'}catch{}
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let modalOpen=false;const canAnimate=()=>!motionPaused&&!reduced.matches&&!modalOpen;
const motionSignal=()=>window.dispatchEvent(new Event('goxo:motion'));
function updateMotionButtons(){const paused=motionPaused||reduced.matches;document.documentElement.dataset.motion=paused?'off':'on';const b=$('#motion-toggle');text(b,reduced.matches?say('Movimiento reducido','Reduced motion'):paused?say('Activar movimiento','Enable motion'):say('Pausar movimiento','Pause motion'));b?.setAttribute('aria-pressed',String(paused));if(b)b.disabled=reduced.matches;const h=$('#hero-motion');if(h){h.textContent=paused?'▷':'Ⅱ';h.setAttribute('aria-label',paused?say('Activar animaciones','Enable animations'):say('Pausar animaciones','Pause animations'));h.disabled=reduced.matches}motionSignal()}
function toggleMotion(){motionPaused=!motionPaused;localWrite('goxo:motion',motionPaused?'off':'on');updateMotionButtons()}
$('#motion-toggle')?.addEventListener('click',toggleMotion);$('#hero-motion')?.addEventListener('click',toggleMotion);on(reduced,'change',updateMotionButtons);
gsap.registerPlugin(ScrollTrigger);
let activeTerritory=seed.tours[0].id;
function selectTerritory(id:string){const tour=state.tours.find((t:any)=>t.id===id&&t.published);if(!tour)return false;activeTerritory=id;const img=$('#hero-landscape');if(img){gsap.killTweensOf(img);const apply=()=>{img.src=tour.image;img.alt=copy(tour.location)};if(canAnimate()){const preload=new Image();preload.src=tour.image;preload.decode().then(()=>{if(activeTerritory!==id)return;if(!canAnimate()){apply();gsap.set(img,{opacity:1});return}gsap.to(img,{opacity:.25,duration:.45,ease:'sine.inOut',onComplete:()=>{apply();gsap.to(img,{opacity:1,duration:.8,ease:'sine.inOut'})}})}).catch(()=>{if(activeTerritory===id)gsap.set(img,{opacity:1})})}else{apply();gsap.set(img,{opacity:1})}}$$('[data-territory]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.territory===id)));const loc=$('#hero-location');if(loc)translated(loc,{es:`${tour.number} / ${tour.short.es.toUpperCase()}`,en:`${tour.number} / ${tour.short.en.toUpperCase()}`});return true}
$$('[data-territory]').forEach(b=>b.addEventListener('click',()=>selectTerritory(b.dataset.territory)));
let selectedFilter='all';
function filterTours(category:string){if(!['all','costa','vino','gastronomia','cultura'].includes(category))throw new Error('Unknown category');selectedFilter=category;let count=0;$$('[data-tour-card]').forEach(card=>{const tour=state.tours.find((t:any)=>t.id===card.dataset.tourCard);card.hidden=!tour?.published||(category!=='all'&&tour.category!==category);if(!card.hidden)count++});$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===category)));if($('#tours-empty'))$('#tours-empty').hidden=count>0;ScrollTrigger.refresh();return count}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>filterTours(b.dataset.filter)));
function element(tag:string,className='',content=''){const el=document.createElement(tag);if(className)el.className=className;if(content)el.textContent=content;return el}
function buildCard(tour:any){
 const card=element('article','tour-card');card.dataset.tourCard=tour.id;card.dataset.category=tour.category;
 const href=localizedHref(tourHref(tour,baseIds),lang),link=element('a','tour-card-photo') as HTMLAnchorElement;link.href=href;link.setAttribute('aria-label',copy(tour.short));
 if(tour.image){const img=element('img') as HTMLImageElement;img.src=tour.image;img.alt=copy(tour.imageAlt||{es:'',en:''});img.loading='lazy';img.width=1200;img.height=900;img.dataset.tourImage=tour.id;link.append(img)}else link.append(element('span','tour-photo-pending'));
 const body=element('div','tour-card-body'),name=element('h3'),description=element('p','tour-description'),meta=element('div','tour-card-meta');translated(name,tour.short);name.dataset.tourName=tour.id;translated(description,tour.description);
 for(const value of [tour.location,tour.duration,{es:'Experiencia privada',en:'Private experience'},tour.guests||{es:'Grupo a consultar',en:'Group size on request'}]){const span=element('span');translated(span,value);meta.append(span)}
 const cta=element('a','button',say('Consultar disponibilidad','Check Availability')) as HTMLAnchorElement;cta.href=localizedHref('/contact/?tour='+encodeURIComponent(tour.id),lang);
 const more=element('a','text-link',say('Ver experiencia','View experience')) as HTMLAnchorElement;more.href=href;
 body.append(name,description,meta,cta,more);card.append(link,body);return card;
}
let currentTour:any=null;
function syncPublic(){
 const grid=$('#tours-grid');if(grid&&isPreview){state.tours.forEach((tour:any)=>{let card=Array.from(grid.children).find((c:any)=>c.dataset.tourCard===tour.id);if(card){card.replaceWith(buildCard(tour))}else grid.append(buildCard(tour))});filterTours(selectedFilter)}
 $$('[data-territory]').forEach(button=>{button.hidden=!state.tours.find((tour:any)=>tour.id===button.dataset.territory&&tour.published)});
 if($('#hero-landscape')){const t=state.tours.find((t:any)=>t.id===activeTerritory);if(t){$('#hero-landscape').src=t.image;$('#hero-landscape').alt=copy(t.location)}}
 const detail=$('[data-detail-id]');if(detail){const id=detail.dataset.detailId==='custom'?new URLSearchParams(location.search).get('id'):detail.dataset.detailId;const tour=state.tours.find((t:any)=>t.id===id);if(!tour||(!tour.published&&!new URLSearchParams(location.search).has('preview'))){detail.replaceChildren();detail.className='section-pad error-page';detail.append(element('h1','',say('No disponible','Unavailable')),element('p','',say('Esta experiencia no está visible en tu catálogo.','This experience is not visible in your catalogue.')));const a=element('a','button',say('Volver al catálogo','Back to catalogue')) as HTMLAnchorElement;a.href='/experiencias/';detail.append(a);return}currentTour=tour;if(isPreview)document.title=copy(tour.short)+' · GOXO';if(isPreview)$$('[data-bind]').forEach(el=>translated(el,tour[el.dataset.bind]));$$('[data-bind-image]').forEach(el=>{el.src=tour.image;el.alt=copy(tour.imageAlt||{es:'',en:''})});$$('[data-tour-contact]').forEach(a=>a.href=localizedHref('/contact/?tour='+encodeURIComponent(tour.id),lang));$$('[data-tour-whatsapp]').forEach(a=>a.href='https://wa.me/34644714642?text='+encodeURIComponent(say('Kaixo, me interesa ','Kaixo, I’m interested in ')+copy(tour.short)));$$('[data-tour-immersive]').forEach(b=>b.hidden=!tour.immersive);
 const route=$('#route-grid');if(route&&isPreview){route.replaceChildren();tour.stops.forEach((stop:any,i:number)=>{const a=element('article','route-step'),h=element('h3'),p=element('p');translated(h,stop);translated(p,tour.stopCopy[i]);a.append(element('span','',String(i+1).padStart(2,'0')),h,p);route.append(a)});}
 for(const field of ['includes','excludes']){const list=$('#tour-'+field);if(!list)continue;list.replaceChildren();tour[field].forEach((item:any)=>{const li=element('li');translated(li,item);list.append(li)})}renderDetailGallery();
 }
 const select=$('#contact-tour');if(select){const selected=select.value||new URLSearchParams(location.search).get('tour');select.replaceChildren();const opt=element('option','',say('Quiero una recomendación','I’d like a recommendation')) as HTMLOptionElement;opt.value='personalizada';select.append(opt);state.tours.filter((t:any)=>t.published).forEach((tour:any)=>{const o=element('option','',copy(tour.short)) as HTMLOptionElement;o.value=tour.id;select.append(o)});if(Array.from(select.options).some((o:any)=>o.value===selected))select.value=selected;}
}
function renderDetailGallery(){const grid=$('#detail-gallery');if(!grid||!currentTour)return;grid.replaceChildren();const photos=currentTour.gallery.length?currentTour.gallery:[currentTour.image];photos.forEach((src:string,i:number)=>{const button=element('button','gallery-tile');button.setAttribute('aria-label',say('Ampliar fotografía ','Expand photograph ')+(i+1));const img=element('img') as HTMLImageElement;img.src=src;img.alt=copy(imageAlts[src]);img.loading='lazy';img.width=1000;img.height=700;button.append(img,element('span','',say('Ampliar ↗','Expand ↗')));button.addEventListener('click',()=>openGallery(photos,i,copy(currentTour.short)));grid.append(button)})}
const mediaDialog=$('#media-dialog') as HTMLDialogElement;const immersiveDialog=$('#immersive-dialog') as HTMLDialogElement;let previousFocus:HTMLElement|null=null;
function openDialog(dialog:HTMLDialogElement){previousFocus=document.activeElement as HTMLElement;dialog.showModal();modalOpen=true;motionSignal();dialog.querySelector<HTMLButtonElement>('[data-close-dialog]')?.focus();if(canAnimate())gsap.from(dialog,{opacity:0,duration:.4});}
function closeDialog(dialog:HTMLDialogElement){dialog.close()}
$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));
for(const dialog of [mediaDialog,immersiveDialog].filter(Boolean)){dialog.addEventListener('click',(e)=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();const p=e as MouseEvent;if(p.clientX<r.left||p.clientX>r.right||p.clientY<r.top||p.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{modalOpen=false;motionSignal();previousFocus?.focus()})}
let galleryPhotos:string[]=[],galleryPosition=0,galleryTitle='';
function showGalleryImage(){const img=$('#lightbox-image');img.hidden=false;img.src=galleryPhotos[galleryPosition];img.alt=copy(imageAlts[galleryPhotos[galleryPosition]]);$('#lightbox-video').hidden=true;text($('#media-title'),galleryTitle);text($('#gallery-count'),`${galleryPosition+1} / ${galleryPhotos.length}`);text($('#media-description'),'');$('.gallery-controls').hidden=galleryPhotos.length<2}
function openGallery(photos:string[],index:number,title:string){galleryPhotos=photos;galleryPosition=index;galleryTitle=title;showGalleryImage();openDialog(mediaDialog)}
$('#gallery-prev')?.addEventListener('click',()=>{galleryPosition=(galleryPosition-1+galleryPhotos.length)%galleryPhotos.length;showGalleryImage()});$('#gallery-next')?.addEventListener('click',()=>{galleryPosition=(galleryPosition+1)%galleryPhotos.length;showGalleryImage()});mediaDialog.addEventListener('keydown',(e)=>{if($('#lightbox-image').hidden)return;if(e.key==='ArrowLeft')$('#gallery-prev').click();if(e.key==='ArrowRight')$('#gallery-next').click()});
function openFilm(){if(immersiveDialog?.open)immersiveDialog.close();const video=$('#lightbox-video') as HTMLVideoElement;$('#lightbox-image').hidden=true;video.hidden=false;video.src=seed.media.video;video.poster=seed.media.coast;$('.gallery-controls').hidden=true;text($('#media-title'),say('Gaztelugatxe, desde el aire.','Gaztelugatxe, from the air.'));text($('#media-description'),say('Video real de Quahadi · CC BY-SA 4.0 · Adaptado a MP4 sin audio.','Real footage by Quahadi · CC BY-SA 4.0 · Adapted to MP4 without audio.'));openDialog(mediaDialog);video.play().catch(()=>{})}
$$('[data-open-film]').forEach(b=>b.addEventListener('click',openFilm));mediaDialog.addEventListener('close',()=>{const video=$('#lightbox-video');video.pause();video.removeAttribute('src');video.load()});$('#lightbox-image')?.addEventListener('error',()=>text($('#media-description'),say('No se pudo cargar esta imagen. Prueba otra fotografía.','This image could not load. Try another photograph.')));$('#lightbox-video')?.addEventListener('error',()=>text($('#media-description'),say('No se pudo reproducir el video. Cierra y vuelve a intentarlo.','The video could not play. Close and try again.')));
const contactForm=$('#contact-form') as HTMLFormElement;
if(contactForm){const date=contactForm.elements.namedItem('date') as HTMLInputElement;const today=new Date();date.min=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');contactForm.addEventListener('input',()=>{$('#contact-result').hidden=true});contactForm.addEventListener('submit',(e)=>{e.preventDefault();if(!contactForm.reportValidity())return;const data=new FormData(contactForm);try{const tour=state.tours.find((t:any)=>t.id===data.get('tour'));const message=makeWhatsAppMessage({name:String(data.get('name')),email:String(data.get('email')),guests:Number(data.get('guests')),date:String(data.get('date')||''),tourLang:String(data.get('tourLang')||''),message:String(data.get('message')||''),tour:tour?copy(tour.short):say('Una experiencia personalizada','A personalised experience')},lang);text($('#contact-preview'),message);$('#contact-whatsapp').href='https://wa.me/34644714642?text='+encodeURIComponent(message);$('#contact-result').hidden=false;$('#contact-whatsapp').focus()}catch{toast(say('Revisa los datos de tu consulta.','Please review your enquiry details.'))}})}
let draft:any=null,dirty=false,uploadBusy=false,adminSceneOrder=[...state.sceneOrder];
const adminForm=$('#admin-form') as HTMLFormElement;
function field(name:string):any{return adminForm?.elements.namedItem(name)}
function renderAdminList(){const list=$('#admin-tour-list');if(!list)return;list.replaceChildren();state.tours.forEach((tour:any)=>{const b=element('button','admin-tour-button',copy(tour.short)+(tour.published?'':say(' · Borrador',' · Draft')));b.setAttribute('aria-pressed',String(tour.id===draft?.id));b.addEventListener('click',()=>{if(dirty&&!confirm(say('¿Descartar los cambios sin guardar?','Discard unsaved changes?')))return;loadDraft(tour)});list.append(b)})}
function draftLink(){if(!draft)return;const href=tourHref(draft,baseIds);$('#admin-preview').href=href+(href.includes('?')?'&':'?')+'preview=true'}
function renderAdminMedia(){if(!draft)return;$('#admin-cover-preview').src=draft.image;const grid=$('#admin-gallery');grid.replaceChildren();draft.gallery.forEach((src:string,i:number)=>{const wrap=element('div','admin-gallery-item'),img=element('img') as HTMLImageElement;img.src=src;img.alt=say('Foto ','Photo ')+(i+1);const b=element('button','','×');b.type='button';b.setAttribute('aria-label',say('Quitar foto ','Remove photo ')+(i+1));b.addEventListener('click',()=>{draft.gallery.splice(i,1);dirty=true;renderAdminMedia()});wrap.append(img,b);grid.append(wrap)})}
function renderAdminScenes(){const list=$('#admin-scenes');list.replaceChildren();adminSceneOrder.forEach((id:string,i:number)=>{const scene=seed.media.panoramas.find((s:any)=>s.id===id);const row=element('div','admin-scene-row'),img=element('img') as HTMLImageElement;img.src=scene.preview;img.alt='';row.append(img,element('span','',copy(scene.label)+' · '+scene.title));for(const [delta,label] of [[-1,'↑'],[1,'↓']] as const){const b=element('button','',label);b.type='button';b.disabled=i+delta<0||i+delta>=adminSceneOrder.length;b.setAttribute('aria-label',(delta<0?say('Subir ','Move up '):say('Bajar ','Move down '))+scene.title);b.addEventListener('click',()=>{[adminSceneOrder[i],adminSceneOrder[i+delta]]=[adminSceneOrder[i+delta],adminSceneOrder[i]];dirty=true;renderAdminScenes()});row.append(b)}list.append(row)})}
function loadDraft(tour:any){draft=structuredClone(tour);dirty=false;adminForm.reset();field('id').value=draft.id;for(const key of ['short','name','location','duration','description','story','faq'])for(const language of ['es','en'])field(key+'_'+language).value=draft[key][language];for(const key of ['stops','stopCopy','includes','excludes'])for(const language of ['es','en'])field(key+'_'+language).value=draft[key].map((v:any)=>v[language]).join('\n');field('category').value=draft.category;field('immersive').checked=draft.immersive;field('published').checked=draft.published;renderAdminList();renderAdminMedia();adminSceneOrder=[...state.sceneOrder];renderAdminScenes();draftLink();text($('#admin-status'),say('Editando una copia. Guarda para aplicar los cambios.','Editing a draft. Save to apply your changes.'))}
function persist(next:any){try{validateState(next,sceneIds);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));state=next;return true}catch{toast(say('No se pudo guardar. El almacenamiento puede estar lleno o bloqueado. Exporta una copia antes de continuar.','Could not save. Storage may be full or blocked. Export a copy before continuing.'));return false}}
async function optimiseUpload(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>3*1024*1024)throw new Error('Invalid image');const url=URL.createObjectURL(file);try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=url});const scale=Math.min(1,1300/img.width,1300/img.height);const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image unavailable');ctx.fillStyle='#f5f0e8';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.8)}finally{URL.revokeObjectURL(url)}}
if(adminForm){renderAdminList();if(state.tours.length)loadDraft(state.tours[0]);else adminForm.hidden=true;adminForm.addEventListener('input',()=>dirty=true);adminForm.addEventListener('submit',(event)=>{event.preventDefault();if(uploadBusy){toast(say('Espera a que terminen las fotografías.','Wait for the photographs to finish.'));return}if(!draft||!adminForm.reportValidity())return;const updated=structuredClone(draft);for(const key of ['short','name','location','duration','description','story','faq'])for(const language of ['es','en'])updated[key][language]=field(key+'_'+language).value.trim();for(const key of ['stops','stopCopy','includes','excludes']){const es=field(key+'_es').value.split('\n').map((v:string)=>v.trim()).filter(Boolean),en=field(key+'_en').value.split('\n').map((v:string)=>v.trim()).filter(Boolean);if(es.length!==en.length){toast(say('Cada lista debe tener la misma cantidad de líneas en español e inglés.','Each list must have the same number of Spanish and English lines.'));return}updated[key]=es.map((v:string,i:number)=>({es:v,en:en[i]}))}if(updated.stops.length!==updated.stopCopy.length){toast(say('Añade una descripción para cada parada.','Add a description for every stop.'));return}updated.category=field('category').value;updated.immersive=field('immersive').checked;updated.published=field('published').checked;const next=structuredClone(state);const index=next.tours.findIndex((t:any)=>t.id===updated.id);if(index>=0)next.tours[index]=updated;else next.tours.push(updated);next.sceneOrder=[...adminSceneOrder];if(persist(next)){draft=updated;dirty=false;renderAdminList();draftLink();text($('#admin-status'),say('Guardado en este navegador. Ya puedes revisar el catálogo o la vista previa.','Saved in this browser. You can now check the catalogue or preview.'));toast(say('Experiencia guardada.','Experience saved.'))}});
$('#admin-new').addEventListener('click',()=>{if(dirty&&!confirm(say('¿Descartar los cambios sin guardar?','Discard unsaved changes?')))return;adminForm.hidden=false;const newTour=structuredClone(seed.tours[0]);newTour.id='experiencia-'+crypto.randomUUID().slice(0,8);newTour.number=String(state.tours.length+1).padStart(2,'0');newTour.short={es:'Nueva experiencia',en:'New experience'};newTour.name={es:'Tu próxima historia',en:'Your next story'};newTour.description={es:'Describe lo que hará especial esta experiencia.',en:'Describe what will make this experience special.'};newTour.story={es:'',en:''};newTour.location={es:'Por definir',en:'To be defined'};newTour.duration={es:'Por definir',en:'To be defined'};newTour.stops=[];newTour.stopCopy=[];newTour.includes=[];newTour.excludes=[];newTour.faq={es:'Detalles pendientes de confirmar.',en:'Details to be confirmed.'};newTour.gallery=[newTour.image];newTour.published=false;newTour.immersive=false;loadDraft(newTour);dirty=true;field('short_es').focus()});
for(const [selector,isCover] of [['#admin-cover',true],['#admin-gallery-upload',false]] as const){$(selector).addEventListener('change',async(event:Event)=>{const target=event.target as HTMLInputElement;const files=Array.from(target.files||[]);if(!files.length||!draft)return;if(!isCover&&draft.gallery.length+files.length>8){toast(say('Esta demo admite hasta 8 fotos por galería.','This demo allows up to 8 photographs per gallery.'));target.value='';return}uploadBusy=true;const buttons=$$('button[type=submit]');buttons.forEach(b=>b.disabled=true);text($('#admin-status'),say('Preparando fotografías…','Preparing photographs…'));try{const results=[];for(const file of files)results.push(await optimiseUpload(file));if(isCover)draft.image=results[0];else draft.gallery.push(...results);dirty=true;renderAdminMedia();text($('#admin-status'),say('Fotos preparadas. Guarda para conservarlas.','Photographs prepared. Save to keep them.'))}catch{toast(say('Usa JPG, PNG o WebP de hasta 3 MB. No se modificaron las fotos guardadas.','Use JPG, PNG or WebP up to 3 MB. Saved photographs were not changed.'))}finally{uploadBusy=false;buttons.forEach(b=>b.disabled=false);target.value=''}})}
$('#admin-export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='goxo-contenido-demo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);if(dirty)toast(say('Se exportó la última versión guardada. Tienes cambios pendientes.','Exported the last saved version. You have unsaved changes.'))});$('#admin-import-button').addEventListener('click',()=>$('#admin-import').click());$('#admin-import').addEventListener('change',async(e:Event)=>{const target=e.target as HTMLInputElement,file=target.files?.[0];if(!file)return;try{if(file.size>8*1024*1024)throw new Error();const next=validateState(JSON.parse(await file.text()),sceneIds);if(!confirm(say('¿Sustituir el contenido de esta demo por la copia importada?','Replace the demo content with this backup?')))return;if(persist(next)){dirty=false;location.reload()}}catch{toast(say('La copia no tiene un formato GOXO válido. No se cambió tu contenido.','The backup is not a valid GOXO format. Your content was not changed.'))}finally{target.value=''}});$('#admin-reset').addEventListener('click',()=>{if(confirm(say('¿Restaurar la demo? Se perderán los cambios guardados en este navegador.','Reset the demo? Changes saved in this browser will be lost.'))){if(persist(structuredClone(defaults))){dirty=false;location.reload()}}});$('#admin-delete').addEventListener('click',()=>{if(!draft||!confirm(say('¿Eliminar esta experiencia de tu demo?','Delete this experience from your demo?')))return;const next=structuredClone(state);next.tours=next.tours.filter((t:any)=>t.id!==draft.id);if(persist(next)){dirty=false;if(state.tours.length)loadDraft(state.tours[0]);else{draft=null;adminForm.hidden=true;renderAdminList()}}});on(window,'beforeunload',(e)=>{if(dirty){e.preventDefault();e.returnValue=''}});}
on(window,'storage',(e)=>{if(e.key===STORAGE_KEY){if(adminForm){toast(say('El contenido cambió en otra pestaña. Recarga antes de editar.','Content changed in another tab. Reload before editing.'));return}try{state=e.newValue?validateState(JSON.parse(e.newValue),sceneIds):structuredClone(defaults);syncPublic()}catch{}}});
translate();syncPublic();updateMotionButtons();
on(window,'goxo:motion',()=>{const img=$('#hero-landscape');if(img&&!canAnimate()){gsap.killTweensOf(img);const tour=state.tours.find((t:any)=>t.id===activeTerritory);if(tour){img.src=tour.image;img.alt=copy(tour.location)}gsap.set(img,{opacity:1})}});
if(contactForm){const selected=new URLSearchParams(location.search).get('tour');if(selected&&state.tours.some((t:any)=>t.id===selected&&t.published))$('#contact-tour').value=selected;}
const lifecycle=new AbortController();
const context=(document as any).modelContext;
if(context?.registerTool){const specs=[{name:'list_goxo_experiences',title:'List GOXO experiences',description:'Read published experiences available in the current prototype.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({experiences:state.tours.filter((t:any)=>t.published).map((t:any)=>({id:t.id,title:copy(t.short),category:t.category,url:tourHref(t,baseIds)}))})}];if($('#tours-grid'))specs.push({name:'filter_goxo_experiences',title:'Filter GOXO experiences',description:'Filter the visible catalogue by category. Does not book or contact anyone.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['all','costa','vino','gastronomia','cultura']}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||typeof input.category!=='string')throw new Error('Category required');return {visibleCount:filterTours(input.category),category:selectedFilter}}} as any);for(const spec of specs){try{Promise.resolve(context.registerTool(spec,{signal:lifecycle.signal})).catch(()=>{})}catch{}}}
on(window,'pagehide',()=>{lifecycle.abort();gsap.killTweensOf('#hero-landscape');ScrollTrigger.getAll().forEach(t=>t.kill());$('#lightbox-video')?.pause()});


return ()=>{events.abort();headerObserver?.disconnect();languageRequest?.abort();lifecycle.abort();gsap.killTweensOf('#hero-landscape');ScrollTrigger.getAll().forEach(t=>t.kill());document.querySelectorAll('video').forEach(video=>video.pause());};
}
let cleanupPage:(()=>void)|undefined;
document.addEventListener('astro:before-swap',()=>cleanupPage?.());
document.addEventListener('astro:page-load',()=>{cleanupPage?.();cleanupPage=initializePage();});
