import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateState,safeImage,makeWhatsAppMessage,tourHref} from '../src/scripts/state.ts';
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
const seed=JSON.parse(html.match(/<script id="goxo-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);
const sceneIds=seed.media.panoramas.map(p=>p.id);
const initial={version:1,tours:seed.tours,sceneOrder:sceneIds};
test('official baseline contains five tours with optional pending media',()=>{const value=validateState(initial,sceneIds);assert.equal(value.tours.length,5);assert.ok(value.tours.every(t=>t.guests.en==='2–8 guests'));value.tours[0].short.es='Edited';assert.notEqual(initial.tours[0].short.es,'Edited')});
test('adding, unpublishing and deleting experiences preserves valid state',()=>{const value=structuredClone(initial);const tour={...structuredClone(value.tours[0]),id:'my-new-tour',published:false};value.tours.push(tour);assert.equal(validateState(value,sceneIds).tours.length,6);value.tours=value.tours.filter(t=>t.id!==tour.id);assert.equal(validateState(value,sceneIds).tours.length,5)});
test('malformed imports and duplicate ids are rejected',()=>{assert.throws(()=>validateState(null,sceneIds));assert.throws(()=>validateState({version:4,tours:[]},sceneIds));const value=structuredClone(initial);value.tours.push(value.tours[0]);assert.throws(()=>validateState(value,sceneIds));});
test('invalid scene references and missing translations are rejected',()=>{const value=structuredClone(initial);value.sceneOrder=['missing',...sceneIds.slice(1)];assert.throws(()=>validateState(value,sceneIds));const second=structuredClone(initial);delete second.tours[0].name.en;assert.throws(()=>validateState(second,sceneIds))});
test('script and SVG image payloads cannot enter stored content',()=>{for(const value of ['javascript:alert(1)','data:image/svg+xml,<svg/>','/media/../../secret.png','https://example.com/tracker.jpg'])assert.equal(safeImage(value),false);assert.equal(safeImage('/media/gaztelugatxe.webp'),true);assert.equal(safeImage('data:image/jpeg;base64,YWJjZA=='),true)});
test('gallery cap and incomplete itineraries are rejected',()=>{const value=structuredClone(initial);value.tours[0].gallery=Array(9).fill('/media/gaztelugatxe.webp');assert.throws(()=>validateState(value,sceneIds));const second=structuredClone(initial);second.tours[0].stopCopy.pop();assert.throws(()=>validateState(second,sceneIds))});
test('WhatsApp message preserves accents, ampersands and selected tour',()=>{const msg=makeWhatsAppMessage({name:'María & José',email:'test@example.com',guests:2,date:'2026-12-10',message:'Sin marisco 🌊',tour:'Costa Vasca'});const url='https://wa.me/34644714642?text='+encodeURIComponent(msg);assert.equal(new URL(url).searchParams.get('text'),msg);assert.match(msg,/María & José/);assert.match(msg,/Costa Vasca/);assert.match(msg,/Sin marisco 🌊/)});
test('guest boundaries and invalid contact fields reject without sending',()=>{const input={name:'Miguel',email:'test@example.com',guests:2,date:'',message:'',tour:'Rioja'};assert.match(makeWhatsAppMessage(input,'en'),/Guests: 2/);assert.match(makeWhatsAppMessage({...input,guests:8}),/Personas: 8/);for(const guests of [1,9,1.5,NaN])assert.throws(()=>makeWhatsAppMessage({...input,guests}));for(const email of ['', 'invalid', 'a b@example.com'])assert.throws(()=>makeWhatsAppMessage({...input,email}));assert.throws(()=>makeWhatsAppMessage({...input,name:' '}))});
test('new records have a working generic route rather than a nonexistent static page',()=>{assert.equal(tourHref({id:'costa-vasca'},['costa-vasca']),'/experiencias/costa-vasca/');assert.equal(tourHref({id:'new-tour'},[]),'/experiencias/detalle/?id=new-tour')});

test('tour language is optional, localised and rejected when unknown',()=>{const input={name:'Endika',email:'test@example.com',guests:2,date:'',message:'',tour:'Pintxos'};assert.doesNotMatch(makeWhatsAppMessage(input),/Idioma del tour/);assert.match(makeWhatsAppMessage({...input,tourLang:'es'}),/Idioma del tour: español/);assert.match(makeWhatsAppMessage({...input,tourLang:'en'},'en'),/Preferred language: English/);for(const tourLang of ['fr','ES','<script>'])assert.throws(()=>makeWhatsAppMessage({...input,tourLang}))});
